
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-without-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build 
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: build/libs/demo-0.0.2-SNAPSHOT.jar
      - name: Build and tag Docker image
        run: docker build -t department-image-by-github-action .
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image to Docker Hub
        run: |
          docker tag department-image-by-github-action ${{ secrets.DOCKER_USERNAME }}/department-image-by-github-action
          docker push ${{ secrets.DOCKER_USERNAME }}/department-image-by-github-action
